logging:
  level:
    com.panther: debug
  #日志路径 eg:当前磁盘根路径下创建spring文件夹和log文件夹   /spring/log
  path:
  #日志文件  C:/xxxx.log
  file:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} === [%thread] === %-5level === %logger{50} === %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.139.129:3306/security-demo?useUnicode=yes&characterEncoding=utf-8
    username: root
    password: root1234
  session:
    store-type: none
#  security:
#    user:
#      name: 1
#      password: 1

#用户可以自定义登录页面 默认是singIn.html
panther:
  security:
#    browser:
#      loginPage: '/demo-signIn.html'
#      loginType: REDIRECT
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*
server:
  port: 9001