spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
  #druid:
  datasource:
    url: jdbc:mysql://192.168.139.129:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #concurrency  消费者数量相关
  #prefetch 每次从连接池取的数量
  #default-requeue-rejected 消费重试
  rabbitmq:
    host: 192.168.139.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
#mybatis
mybatis:
  type-aliases-package: com.panther.seckill.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/panther/seckill/dao/*.xml

redis:
  host: 192.168.139.129
  port: 6379
  timeout: 5
  password: 123456
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500




















